version: "2"

services:
  github-exporter:
    tty: true
    stdin_open: true
    expose:
      - 9171
    ports:
      - 9171:9171
    image: infinityworks/github-exporter:latest
    environment:
      - ORGS=form3tech-oss
      - GITHUB_TOKEN=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
